### ISSUE TITLE
Search error on the word "souls"

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#352]
# Story

When searching text in works created from file  the work `The Mysticism of Ignatius: Pdf 1, Page 10` throws an error in the terminal when searching for the word `souls`. The search spins and never completes in the UI. This happened for two different people when running in development mode.

- We did not find any other words which failed on that page.
- The word IS found in the OCR text file.
- We did not find any other pages where the word souls failed.

```
undefined local variable or method `default' for #<BlacklightIiifSearch::IiifSearchAnnotation:0x0000ffff7239c7f0> excluded from capture: DSN not set

NameError (undefined local variable or method `default' for #<BlacklightIiifSearch::IiifSearchAnnotation:0x0000ffff7239c7f0>):

/usr/local/bundle/bundler/gems/iiif_print-e3384284a999/lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb:39:in `coordinates'
/usr/local/bundle/bundler/gems/iiif_print-e3384284a999/lib/iiif_print/blacklight_iiif_search/annotation_decorator.rb:20:in `canvas_uri_for_annotation'
```

# Acceptance Criteria

- [ ] Search does not error.

# Screenshots / Video

<details>
<summary>Spinning search</summary>

![Screenshot 2023-04-04 at 4 13 23 PM](https://user-images.githubusercontent.com/17851674/229909772-d3beac48-3959-4a97-a718-03bd9d8acf48.png)

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by laritakr** [comment]
Additional note: the error that it hits appears to be because default is not a defined method... there is a default_array method that may have been meant to be used. When using that method, the search did not fail but it returned the garbage coordinates for the second occurrence.
