### ISSUE TITLE
Batch edit works to change visibility

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#56]
# Proposal

Close this ticket as "won't fix".  Instead favor using Bulkrax for batch edits; this will require some training.  [See comment below for more details](https://github.com/scientist-softserv/adventist-dl/issues/56#issuecomment-1318640762).

# Summary
Trying to batch edit works to change visibility didn't work for me yesterday. It gave the error message "We're sorry but something went wrong. Check logs for more info."

# Acceptance Criteria

- [ ] Batch editing works to change visibility works

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jeremyf** [comment]
The underlying exception is `NoMethodError in Hyrax::BatchEditsController#edit undefined method `to_a' for "1967-04-22":String Did you mean? to_f to_d to_c to_s to_i to_r`

<details>
<summary>Call Stack</summary>

```shell
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:70:in `block (2 levels) in initialize_combined_fields'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:68:in `each'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:68:in `block in initialize_combined_fields'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:66:in `each'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:66:in `each_with_object'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:66:in `initialize_combined_fields'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:21:in `initialize'
hyrax (2.9.5) app/controllers/hyrax/batch_edits_controller.rb:19:in `new'
hyrax (2.9.5) app/controllers/hyrax/batch_edits_controller.rb:19:in `edit'
actionpack (5.2.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.6) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sentry-raven (2.13.0) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.6) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.6) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.6) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
railties (5.2.6) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.6) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
is_it_working (1.1.0) lib/is_it_working/handler.rb:48:in `call'
apartment (2.2.1) lib/apartment/elevators/generic.rb:21:in `block in call'
apartment (2.2.1) lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
apartment (2.2.1) lib/apartment/elevators/generic.rb:21:in `call'
apartment (2.2.1) lib/apartment/reloader.rb:18:in `call'
rack (2.2.3) lib/rack/deflater.rb:44:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/cookies.rb:670:in `call'
active-fedora (12.1.1) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.6.0) lib/flipflop/feature_cache.rb:12:in `call'
activerecord (5.2.6) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.3.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
sentry-raven (2.13.0) lib/raven/integrations/rack.rb:51:in `call'
secure_headers (6.3.0) lib/secure_headers/middleware.rb:11:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
puma (4.3.8) lib/puma/commonlogger.rb:40:in `call'
puma (4.3.8) lib/puma/configuration.rb:228:in `call'
puma (4.3.8) lib/puma/server.rb:718:in `handle_request'
puma (4.3.8) lib/puma/server.rb:472:in `process_client'
puma (4.3.8) lib/puma/server.rb:328:in `block in run'
puma (4.3.8) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

</details>

**Comment by jeremyf** [comment]
Note fixing the above results in another error:

`ActiveTriples::Relation::ValueError in Hyrax::BatchEditsController#edit
value must be an RDF URI, Node, Literal, or a valid datatype. See RDF::Literal. You provided []`

<details>
<summary>Call Stack</summary>

```shell
active-triples (1.1.1) lib/active_triples/relation.rb:523:in `set_value'
active-triples (1.1.1) lib/active_triples/relation.rb:399:in `block in set'
active-triples (1.1.1) lib/active_triples/relation.rb:399:in `each'
active-triples (1.1.1) lib/active_triples/relation.rb:399:in `set'
active-triples (1.1.1) lib/active_triples/rdf_source.rb:479:in `set_value'
active-fedora (12.1.1) lib/active_fedora/fedora_attributes.rb:33:in `set_value'
active-fedora (12.1.1) lib/active_fedora/attribute_methods/dirty.rb:11:in `set_value'
active-fedora (12.1.1) lib/active_fedora/attributes/property_builder.rb:22:in `creator='
active-fedora (12.1.1) lib/active_fedora/attributes.rb:46:in `[]='
hydra-editor (5.0.4) app/forms/hydra_editor/form.rb:98:in `block in initialize_fields'
hydra-editor (5.0.4) app/forms/hydra_editor/form.rb:98:in `each'
hydra-editor (5.0.4) app/forms/hydra_editor/form.rb:98:in `initialize_fields'
hydra-editor (5.0.4) app/forms/hydra_editor/form.rb:16:in `initialize'
hyrax (2.9.5) app/forms/hyrax/forms/work_form.rb:42:in `initialize'
hyrax (2.9.5) app/forms/hyrax/forms/batch_edit_form.rb:22:in `initialize'
hyrax (2.9.5) app/controllers/hyrax/batch_edits_controller.rb:19:in `new'
hyrax (2.9.5) app/controllers/hyrax/batch_edits_controller.rb:19:in `edit'
actionpack (5.2.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.6) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sentry-raven (2.13.0) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.6) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.6) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.6) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
railties (5.2.6) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.6) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
is_it_working (1.1.0) lib/is_it_working/handler.rb:48:in `call'
apartment (2.2.1) lib/apartment/elevators/generic.rb:21:in `block in call'
apartment (2.2.1) lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `switch'
apartment (2.2.1) lib/apartment/elevators/generic.rb:21:in `call'
apartment (2.2.1) lib/apartment/reloader.rb:18:in `call'
rack (2.2.3) lib/rack/deflater.rb:44:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (5.2.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/cookies.rb:670:in `call'
active-fedora (12.1.1) lib/active_fedora/ldp_cache.rb:26:in `call'
flipflop (2.6.0) lib/flipflop/feature_cache.rb:12:in `call'
activerecord (5.2.6) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.3.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
sentry-raven (2.13.0) lib/raven/integrations/rack.rb:51:in `call'
secure_headers (6.3.0) lib/secure_headers/middleware.rb:11:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
puma (4.3.8) lib/puma/commonlogger.rb:40:in `call'
puma (4.3.8) lib/puma/configuration.rb:228:in `call'
puma (4.3.8) lib/puma/server.rb:718:in `handle_request'
puma (4.3.8) lib/puma/server.rb:472:in `process_client'
puma (4.3.8) lib/puma/server.rb:328:in `block in run'
puma (4.3.8) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

</details>

**Comment by jeremyf** [comment]
I am bringing this up at stand-up because as I've delved into implementations of Hyrax 2.9.6; this functionality is somewhat fragile.

**Comment by jeremyf** [comment]
In talking through the Batch Edit feature, this is something that is presently slated for removal in future Hyku implementations (actually the underlying Hyrax implementation).  First, it has been poorly maintained and as we can see has bugs related to Adventist's data model; Hyrax made assumptions about this batch edit and hard-coded those decisions.

Our strong recommendation, instead of fixing this, is to leverage Bulkrax for batch edits.  This is something to include in our training.

*Note:* I have spent about 45 minutes exploring how to resolve it, and like an onion I keep peeling back layers to the problem that make me cry.

**Comment by jeremyf** [comment]
Closing this issue as we will use the Bulkrax round-trip for testing.
