### ISSUE TITLE
Issues with creating collections/subcollections and/or adding works to them

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#59]
# Summary
From Adventist:
Creating collections and subcollections and/or adding works to them is complex. There are glitches I encountered:

- Trying to add a collection to another collection from within the collection page only shows the user collections I've created. In other locations, I see the complete list of collections on Hyku. Can that be the standard behavior in all places?
- Trying to add a collection to another collection from within the collection page doesn't work anyway. I get a "We're sorry, but something went wrong" message.
- I can't add a subcollection to a collection either (from within the collection edit page on dashboard). I get "We're sorry, but something went wrong."
- From a work page, I can't add a work to a collection unless I created the collection. The drop down will not populate with collections I didn't author. Can this be fixed to offer all existing collections?

# Acceptance Criteria

- [ ] Complete list of collections shows when adding a collection from within the collection page in all locations
- [ ] Adding a collection to another collection from within the collection page works
- [ ] Adding a subcollection to a collection works
- [ ] Works can be added to a collection no matter the author

# Notes
Does this need to be broken down into different tickets?

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by KatharineV** [comment]
From a work page, I can't add a work to a collection unless I created the collection. The drop down will not populate with collections I didn't author. Can this be fixed to offer all existing collections?
Update as of 2022-11-17: I can no longer add works to any collections, even if I created them. Attempting to add a work to a collection generates a message like "You don't have access to any collections. Would you like to create one?" I have eight collections I created in ADL B2 and have been able to add works to them until today.

**Comment by jeremyf** [comment]
Looking into this, I see the following exception:

```
NoMethodError (undefined method `[]' for nil:NilClass):

blacklight_advanced_search (6.4.1) lib/blacklight_advanced_search/advanced_search_builder.rb:57:in `add_advanced_parse_q_to_solr'
blacklight (6.24.0) lib/blacklight/search_builder.rb:147:in `block (2 levels) in processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:146:in `each'
blacklight (6.24.0) lib/blacklight/search_builder.rb:146:in `block in processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:145:in `tap'
blacklight (6.24.0) lib/blacklight/search_builder.rb:145:in `processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:119:in `to_hash'
hyrax (2.9.5) app/services/hyrax/collections/nested_collection_query_service.rb:157:in `child_nesting_depth'
hyrax (2.9.5) app/services/hyrax/collections/nested_collection_query_service.rb:136:in `valid_combined_nesting_depth?'
hyrax (2.9.5) app/forms/hyrax/forms/dashboard/nest_collection_form.rb:80:in `nesting_within_maximum_depth'
```

I'm looking to resolve that issue.

**Comment by jeremyf** [comment]
In talking with SoftServ team members this appears to be a known and lingering bug of Hyku; in part due to the conflict between performance and nested sets.

The tl;dr - with current implementations, nested collections require extensive computational resources to calculate.  Which dramatically slows down import/ingest processing (already slow because of the mime type determination, generation of derivatives, and extraction of OCR).

We are investigating a general solution that is available in later versions of one of our upstream dependencies, but requires careful consideration on how to back port those to existing versions of Hyku.

**Comment by jeremyf** [comment]
We are looking to back port work on upstream Hyrax (see https://github.com/samvera/hyrax/pull/5918) to address this issue.

**Comment by DeonFranklin** [comment]
-Complete list of collections shows when adding a collection
![image](https://user-images.githubusercontent.com/95306716/204882094-f77f0405-e8a7-49f1-9ad7-504880fd0aa4.png)


-Collection successfully created
![image](https://user-images.githubusercontent.com/95306716/204881408-73790a0b-6ac8-407a-8039-dbf3aa3e770a.png)

-Subcollection added to the collection 
![image](https://user-images.githubusercontent.com/95306716/204881580-d841cc48-407b-4ae0-a718-1428d0597aa7.png)

-Work added to the collection
![image](https://user-images.githubusercontent.com/95306716/204881694-962f1460-9860-474b-9cec-87caafb9815c.png)
