### ISSUE TITLE
Collection and subcollection error

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#70]
Attempting to add a subcollection to a collection results in error messages. Error messages occur if you try to add an existing collection to another as a subcollection and/or if you try to "create new collection as subcollection" from within a collection page on the dashboard. This happens on both staging and on production (S2 & B2). See below for screenshots.

![Image](https://user-images.githubusercontent.com/29311858/200075976-18e96aff-57c9-479d-80de-340ca423211e.png)

![Image](https://user-images.githubusercontent.com/29311858/200075987-0b7ddbe5-e9f6-4aa9-b77f-65ae4e512f55.png)

**Comment by jeremyf** [comment]
In development, we get the following error:

```shell
NoMethodError in Hyrax::Dashboard::NestCollectionsController#create_relationship_under

undefined method `[]' for nil:NilClass
Extracted source (around line #57):

#55 
#56       # If the individual field has advanced_parse_q suppressed, punt
*57       return if field_def[:advanced_parse] == false
#58 
#59       solr_direct_params = field_def[:solr_parameters] || {}
#60       solr_local_params = field_def[:solr_local_parameters] || {}

Extracted source (around line #147):

#145       request.tap do |request_parameters|
#146         processor_chain.each do |method_name|
*147           send(method_name, request_parameters)
#148         end
#149       end
#150     end

Extracted source (around line #146):

#144     def processed_parameters
#145       request.tap do |request_parameters|
*146         processor_chain.each do |method_name|
#147           send(method_name, request_parameters)
#148         end
#149       end


Rails.root: /app/samvera/hyrax-webapp

Framework Trace
blacklight_advanced_search (6.4.1) lib/blacklight_advanced_search/advanced_search_builder.rb:57:in `add_advanced_parse_q_to_solr'
blacklight (6.24.0) lib/blacklight/search_builder.rb:147:in `block (2 levels) in processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:146:in `each'
blacklight (6.24.0) lib/blacklight/search_builder.rb:146:in `block in processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:145:in `tap'
blacklight (6.24.0) lib/blacklight/search_builder.rb:145:in `processed_parameters'
blacklight (6.24.0) lib/blacklight/search_builder.rb:119:in `to_hash'
hyrax (2.9.5) app/services/hyrax/collections/nested_collection_query_service.rb:157:in `child_nesting_depth'
hyrax (2.9.5) app/services/hyrax/collections/nested_collection_query_service.rb:136:in `valid_combined_nesting_depth?'
hyrax (2.9.5) app/forms/hyrax/forms/dashboard/nest_collection_form.rb:80:in `nesting_within_maximum_depth'
activesupport (5.2.6) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.6) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
activesupport (5.2.6) lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
activesupport (5.2.6) lib/active_support/callbacks.rb:605:in `catch'
activesupport (5.2.6) lib/active_support/callbacks.rb:605:in `block in default_terminator'
activesupport (5.2.6) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.6) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
activesupport (5.2.6) lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
activemodel (5.2.6) lib/active_model/validations.rb:409:in `run_validations!'
activemodel (5.2.6) lib/active_model/validations.rb:339:in `valid?'
hyrax (2.9.5) app/forms/hyrax/forms/dashboard/nest_collection_form.rb:33:in `save'
hyrax (2.9.5) app/controllers/hyrax/dashboard/nest_collections_controller.rb:33:in `create_relationship_under'
actionpack (5.2.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.6) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
sentry-raven (2.13.0) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.6) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.6) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.6) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.6) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
railties (5.2.6) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.6) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.6) lib/action_dispatch/routing/mapper.rb:19:in `block in 
```

**Comment by jeremyf** [comment]
Here's the code that is failing: 
https://github.com/projectblacklight/blacklight_advanced_search/blob/18f236444af74533c16dd8eaf08a68aba4b2f498/lib/blacklight_advanced_search/advanced_search_builder.rb#L56-L57

**Comment by DeonFranklin** [comment]
Collection and Subcollection were successfully created.

![image](https://user-images.githubusercontent.com/95306716/204880611-3df7a78f-40a6-400c-8f97-fb4e286b7bab.png)


![image](https://user-images.githubusercontent.com/95306716/204880498-7529a0fd-bd0e-48cf-865a-9d3ea70b59f9.png)
